"""Add user model

Revision ID: db2328d0e3d5
Revises: 
Create Date: 2025-03-07 10:53:07.746470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db2328d0e3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_goal_mapping_ibfk_2', 'asset_goal_mapping', type_='foreignkey')
    op.drop_constraint('asset_goal_mapping_ibfk_1', 'asset_goal_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'asset_goal_mapping', 'asset', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_goal_mapping', 'goal', ['goal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('asset_goal_mapping', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_goal_mapping', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'asset_goal_mapping', type_='foreignkey')
    op.drop_constraint(None, 'asset_goal_mapping', type_='foreignkey')
    op.create_foreign_key('asset_goal_mapping_ibfk_1', 'asset_goal_mapping', 'asset', ['asset_id'], ['id'])
    op.create_foreign_key('asset_goal_mapping_ibfk_2', 'asset_goal_mapping', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###
